import { types } from "@circle/all_apis";

export type CryptoPaymentCreationRequest = {
  amount: types.CryptoPaymentsMoney;
  destination: types.CryptoPaymentDestination;
  idempotencyKey: string;
  /**
   * Payment intent uuid which is generated by the create payment intent call
   */
  paymentIntentId: string;
  protocolMetadata: types.MetadataCryptoPayment;
  /**
   * Network fee quote uuid which is returned from the /presign response. Only required when end user pays for gas fee
   */
  quoteId?: string;
  source: types.CryptoPaymentSource;
};
