export enum GetV1PayoutsChainEnum {
  Algo = "ALGO",
  Arb = "ARB",
  Avax = "AVAX",
  Base = "BASE",
  Btc = "BTC",
  Celo = "CELO",
  Eth = "ETH",
  Flow = "FLOW",
  Hbar = "HBAR",
  Near = "NEAR",
  Noble = "NOBLE",
  Op = "OP",
  Pah = "PAH",
  Poly = "POLY",
  Sol = "SOL",
  Trx = "TRX",
  Xlm = "XLM",
}
