export enum VerificationErrorCodeEnum {
  CardAccountIneligible = "card_account_ineligible",
  CardAddressMismatch = "card_address_mismatch",
  CardCvvInvalid = "card_cvv_invalid",
  CardCvvRequired = "card_cvv_required",
  CardExpired = "card_expired",
  CardFailed = "card_failed",
  CardInvalid = "card_invalid",
  CardLimitViolated = "card_limit_violated",
  CardNetworkUnsupported = "card_network_unsupported",
  CardNotHonored = "card_not_honored",
  CardZipMismatch = "card_zip_mismatch",
  CreditCardNotAllowed = "credit_card_not_allowed",
  VerificationDenied = "verification_denied",
  VerificationFailed = "verification_failed",
  VerificationFraudDetected = "verification_fraud_detected",
  VerificationNotSupportedByIssuer = "verification_not_supported_by_issuer",
  VerificationStoppedByIssuer = "verification_stopped_by_issuer",
}
